<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\LumaZhTw\OpenCcConverter.cs" />
    <Compile Include="..\..\src\LumaZhTw\Glossary.cs" />
  </ItemGroup>
</Project>
