"""Approximate OpenCC's build step generate_st_phrases_from_regional_phrases.py for s2twp.

OpenCC generates STPhrases_GeneratedFromRegionalPhrases.txt at build time (it is not in the repo):
each TWPhrases key (Traditional) is projected to Simplified with t2s, and projections of 3+ chars
become Simplified->Traditional-key phrase entries. OpenCC uses its own t2s binary; here we use the
Python `opencc` package's t2s, which may differ slightly. We only use TWPhrases (s2twp needs no HK).
"""
import pathlib
from opencc import OpenCC

d = pathlib.Path(__file__).resolve().parent.parent / "src" / "LumaZhTw" / "Dictionaries"
cc = OpenCC("t2s")
keys = [l.split("\t", 1)[0] for l in (d / "TWPhrases.txt").read_text(encoding="utf-8").splitlines()
        if l and not l.startswith("#") and "\t" in l]
gen = {}
for k in keys:
    s = cc.convert(k)
    if len(s) >= 3:
        gen.setdefault(s, k)
out = d / "STPhrases_GeneratedFromRegionalPhrases.txt"
with out.open("w", encoding="utf-8", newline="\n") as f:
    f.write("# Open Chinese Convert (OpenCC) Dictionary\n# File: STPhrases_GeneratedFromRegionalPhrases.txt\n")
    f.write("# License: Apache-2.0 (see third_party/OpenCC/LICENSE)\n")
    f.write("# Generated by tools/gen_regional_st_phrases.py from TWPhrases.txt keys via t2s\n\n")
    for s in sorted(gen):
        f.write(f"{s}\t{gen[s]}\n")
print(len(gen), "entries ->", out)
